### ISSUE TITLE
Review cookbook doc

### ISSUE THREAD

**Issue by dbu** [symfony-cmf/symfony-cmf-docs#283]
it seems some of the cookbook articles contain configuration (which can be outdated) as well. we should review them as well, or at least add the outdated note, maybe with a link to the config reference into the articles.

see for example 
- http://stackoverflow.com/questions/19127075/createbundle-installation-is-causing-errors
- http://stackoverflow.com/questions/19204361/symfony-cmf-and-sonata-issues

Most cookbook articles should go into book chapters or made sure to not overlap with them:
- [x] creating_cms_using_cmf_and_sonata.rst #239, #49 => integrating into "creating_a_cms/sonata-admin.rst"
- [x] installing_configuring_inline_editing.rst   #239, #49
- [x] installing_configuring_doctrine_phpcr_odm.rst  doctrine/phpcr-odm-documentation#32
- [x] handling_multilang_documents.rst       #257
- [x] using_blockbundle_and_contentbundle.rst #241
- [x] database/choosing_storage_layer.rst

Reviewing those but for now did not move:
- [x] editions/cmf_core.rst  #49
- [x] editions/cmf_sandbox.rst #49
